### PR TITLE
Added cost to all fuel in Career Mode

### PR DESCRIPTION
**Pull request by ijzm**
#1 

I tried following the guidelines you gave me in the first Pull Request, so hopefully all of this should be alright.

The only problem I have is that for some reason it's trying to merge also the last 2 commits I did, this is probably because I suck with github.

I tested this in career, science and sandbox mode, and thankfully Funding.CanAfford returns true in Sandbox/Science, so there's no reason to check the gamemode you are playing.

Hope it is useful.

### CODE REVIEW

**Comment by markusa380** [comment]
Please rebase your changes to the current version of Development, I made a couple of changes.

**Comment by ijzm** [comment]
I'll try doing that as soon as I get access to my computer.

**Comment by markusa380** [comment]
Can't wait, it's gonna be a great addition to the mod!

**Comment by ijzm** [comment]
Ok, I'm pretty sure I successfully rebased. Hopefully everything is alright.

**Comment by markusa380** [comment]
Your code looks good, but I am a little worried about compatibility. If you use a resource from a mod, it isn't in the ressource cost list, which means that the code will break. Can you change it so it will return, for example, a price of zero for all "other" ressources?
Maybe you can even find a better solution! 😉 

EDIT: I will merge the request anyway, so you can have a fresh branch from Develop.

**Comment by ijzm** [comment]
Mh..  good idea would be to move allí the hardcoded variables from simplerefuel.cs to the config file. And also, add a case for when the fuel doesn't match any of the list. That way we can de mod compatibility later and don't worry if someone is using another type of fuel.

I'll see what can I do later

**Comment by markusa380** [comment]
That sounds like a good idea, I hope it's not too hard to map the values in the .cfg to the actual resource types.

**Comment by ijzm** [comment]
I have been able to map all the resources and prices to the CFG, but I have not yet pushed the code as for some reason it's working with every single resource except Oxidizer. I'll push and create a PR as soon as I find and resolve why is that not working.

**Comment by markusa380** [comment]
Any progress? Do you need any help?

**Comment by ijzm** [comment]
I got it working a bit ago. Forgot to push my code. Will be adding it soon.

**Pull request merged**
